server:
  port: 8080
  servlet:
    context-path: /h2-demo

management:
  server:
    port: 9080
  endpoints:
    web:
      exposure:
        include:
          - health
          - info
          - prometheus
  endpoint:
    health:
      show-details: always

spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:employee
    driverClassName: org.h2.Driver
  jpa:
    defer-datasource-initialization: true
    database-platform: org.hibernate.dialect.H2Dialect